"""OAR knowledge base + retrieval for SegAgent.

Maps a free-text clinical query (a treatment site, the word "OAR", a diagnosis,
...) to a *curated* list of organs-at-risk to delineate. The organ lists live in
``knowledge/oar_protocols.json`` and are never generated by the LLM — retrieval
only chooses which curated list applies, so the clinical content stays
auditable.

Matching is hybrid:
  1. keyword / alias match (deterministic, fast)   -> primary path
  2. semantic similarity via the shared embedder    -> fallback for fuzzy queries

The embedder is injected (``embed_fn``) so we reuse VoxTell's already-loaded
Qwen3-Embedding-4B instead of loading a second model.
"""

import json
import re
from typing import Callable, List, Optional, Tuple

import numpy as np

SEMANTIC_MIN_SIM = 0.30  # below this the semantic match is considered too weak


class OARKnowledgeBase:
    def __init__(self, path: str,
                 embed_fn: Optional[Callable[[List[str]], np.ndarray]] = None):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        self.protocols = [p for p in data.get("protocols", []) if p.get("oars")]
        self.embed_fn = embed_fn
        self._doc_embeds = None  # lazily computed (n_protocols, dim)

    # ------------------------------------------------------------- helpers
    @staticmethod
    def _norm(s: str) -> str:
        # Keep CJK characters; only strip punctuation/symbols and lowercase ASCII.
        return re.sub(r"[^\w一-鿿 ]+", " ", s.lower()).strip()

    @staticmethod
    def _l2norm(x: np.ndarray) -> np.ndarray:
        n = np.linalg.norm(x, axis=-1, keepdims=True)
        return x / np.clip(n, 1e-8, None)

    def _keyword_match(self, query: str):
        q = self._norm(query)
        if not q:
            return None
        best = None  # (matched_length, protocol)
        for p in self.protocols:
            for key in [p["site"], *p.get("aliases", [])]:
                kk = self._norm(key)
                if kk and (kk in q or q in kk):
                    if best is None or len(kk) > best[0]:
                        best = (len(kk), p)
        return best[1] if best else None

    def _doc_texts(self) -> List[str]:
        return [
            f'{p["site"]}. ' + ", ".join(p.get("aliases", [])) + ". "
            + p.get("description", "")
            for p in self.protocols
        ]

    def _semantic_match(self, query: str):
        if self.embed_fn is None or not self.protocols:
            return None
        try:
            if self._doc_embeds is None:
                self._doc_embeds = self._l2norm(
                    np.asarray(self.embed_fn(self._doc_texts()), dtype=np.float32))
            q = self._l2norm(
                np.asarray(self.embed_fn([query]), dtype=np.float32))  # (1, dim)
            sims = self._doc_embeds @ q[0]
            idx = int(np.argmax(sims))
            if sims[idx] < SEMANTIC_MIN_SIM:
                return None
            return self.protocols[idx]
        except Exception:
            return None  # never let retrieval crash the agent

    # -------------------------------------------------------------- public
    def lookup(self, query: str) -> Tuple[Optional[dict], Optional[str]]:
        """Return (protocol, how) where how is 'keyword' | 'semantic' | None."""
        # Reject degenerate queries (empty, "...", punctuation only) so they can
        # never fall through to a spurious semantic match.
        if not self._norm(query):
            return None, None
        p = self._keyword_match(query)
        if p is not None:
            return p, "keyword"
        p = self._semantic_match(query)
        if p is not None:
            return p, "semantic"
        return None, None

    def format_observation(self, query: str) -> str:
        """Human/LLM-readable result string for the lookup_oar tool."""
        p, how = self.lookup(query)
        if p is None:
            sites = ", ".join(pp["site"] for pp in self.protocols)
            return (f'lookup_oar("{query}") -> NO MATCH. Known protocols: {sites}. '
                    f"Look at the slices to infer the body region and retry "
                    f"lookup_oar with one of those protocol names; if you cannot "
                    f"tell from the image, ask the user via FINAL.")
        oars = p.get("oars", [])
        joined = "; ".join(oars)
        return (f'lookup_oar("{query}") -> matched "{p["site"]}" (via {how}). '
                f"{len(oars)} OARs to delineate: {joined}. "
                f'Segment them all in one call: segment("{joined}").')
